name: nestjs_cacheable

services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root.abc123
      MYSQL_DATABASE: nestjs_cacheable_test
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--bind-address=0.0.0.0",
    ]

  redis:
    image: redis:latest
    ports:
      - "6381:6379"

  etcd:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6370:6370"
    command: redis-server --port 6370
    environment:
      REDIS_HOST: redis

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: nestjs_cacheable_test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"