name: Add GitHub Release Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: Please refer to [CHANGELOG.md](https://github.com/MAXLZ1/nestjs-cacheable/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
