name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      HOST: 127.0.0.1

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Start services
        run: docker compose -f docker-compose.yml up -d

      - name: Install dependencies
        run: pnpm install

      - name: Unit test
        run: pnpm run test

      - name: E2e test
        run: pnpm run test:e2e
